# ------------------------------------------------------------------------------


- name: Place ~/.gnupg/gpg-agent.conf
  ansible.builtin.copy:
    src: gpg-agent.conf
    dest: ~/.gnupg/gpg-agent.conf
    mode: "0644"

- name: Place ~/.gnupg/gpg.conf
  ansible.builtin.copy:
    src: gpg.conf
    dest: ~/.gnupg/gpg.conf
    mode: "0644"

- name: Place ~/.local/bin/gpg-agent-restart
  ansible.builtin.copy:
    src: gpg-agent-restart.sh
    dest: ~/.local/bin/gpg-agent-restart
    mode: "0744"

- name: Place ~/.local/bin/gpg-agent-sign-temporary-file.sh
  ansible.builtin.copy:
    src: gpg-agent-sign-temporary-file.sh
    dest: ~/.local/bin/gpg-agent-sign-temporary-file
    mode: "0744"


# ------------------------------------------------------------------------------
# Zsh


- name: "zsh : Add init block to {{ zsh_zprofile_middle }}"
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile_middle }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export GPG_TTY=$(tty)
  register: task

- name: "zsh : Compile {{ zsh_zprofile_middle }}"
  when: task.changed
  ansible.builtin.command: zsh -c 'zcompile -R {{ zsh_zprofile_middle }}'


# ------------------------------------------------------------------------------
# Bash


- name: "bash : Add init block to {{ bash_profile_middle }}"
  ansible.builtin.blockinfile:
    path: "{{ bash_profile_middle }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export GPG_TTY=$(tty)


# ------------------------------------------------------------------------------
